apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.nameSpace }}
spec:
  selector:
    app: {{ .Values.applicationName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.port }}
  type: ClusterIP